import { useState } from "react"

function App() {
  const [color, setColor] = useState("olive")
  return (
    <div className="w-half h-screen duration 200 " style={{
      backgroundColor: color
    }}>
      <div>
        <h1 className="bg-white px-80 text-blue shadow-lg text-2xl font-mono leading-normal" >Background Color Changer</h1>
        <p className="bg-green px-10 text-blue shadow-lg font-mono leading-normal px-80" >I made this basic bg color changer by using react library with  the help of hitesh sir(chai aur code)</p>
      </div>
      <div className="fixed flex-wrap justifu-center bottom-12 inset-x-0 px-2">
        <div className="flex flex-wrap justify-center gap-5 shadow-lg bg-white px-3 py-2 rounded-full">

          <button onClick={() => setColor("red")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "red" }}>Red</button>

          <button onClick={() => setColor("orange")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "orange" }}>Orange</button>

          <button onClick={() => setColor("olive")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "olive" }}>olive</button>

          <button onClick={() => setColor("yellow")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "yellow" }}>yellow</button>

          <button onClick={() => setColor("blue")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "blue" }}>blue</button>

          <button onClick={() => setColor("purple")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "purple" }}>purple</button>

          <button onClick={() => setColor("green")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "green" }}>green</button>

          <button onClick={() => setColor("pink")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "pink" }}>pink</button>

          <button onClick={() => setColor("black")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "black" }}>black</button>

          <button onClick={() => setColor("grey")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "grey" }}>grey</button>

          <button onClick={() => setColor("brown")} className="outline-none px-4 py-1 rounded-full text-white shadow-lg" style={{ backgroundColor: "brown" }}>brown</button>

        </div>
      </div>
    </div>
  )
}

export default App


// Layout

// flex - flex
// inline-flex - inline-flex
// block - block
// inline-block - inline-block
// table - table
// inline-table - inline-table
// grid - grid
// inline-grid - inline-grid
// float - float-left, float-right, float-none
// clear - clear-left, clear-right, clear-both, clear-none
// overflow - overflow-auto, overflow-hidden, overflow-visible, overflow-scroll
// position - static, relative, absolute, fixed, sticky
// top - top-0, top-1, top-2, ...
// right - right-0, right-1, right-2, ...
// bottom - bottom-0, bottom-1, bottom-2, ...
// left - left-0, left-1, left-2, ...
// z-index - z-0, z-10, z-20, ...
// Spacing

// margin - m-0, m-1, m-2, ...
// margin-x - mx-0, mx-1, mx-2, ...
// margin-y - my-0, my-1, my-2, ...
// padding - p-0, p-1, p-2, ...
// padding-x - px-0, px-1, px-2, ...
// padding-y - py-0, py-1, py-2, ...
// gap - gap-0, gap-1, gap-2, ...
// Sizing

// width - w-full, w-1/2, w-1/3, ...
// height - h-full, h-1/2, h-1/3, ...
// max-width - max-w-full, max-w-md, max-w-lg, ...
// max-height - max-h-full, max-h-md, max-h-lg, ...
// min-width - min-w-full, min-w-md, min-w-lg, ...
// min-height - min-h-full, min-h-md, min-h-lg, ...
// Typography

// font-family - font-sans, font-serif, font-mono, ...
// font-size - text-xs, text-sm, text-base, text-lg, text-xl, ...
// font-weight - font-thin, font-light, font-normal, font-bold, font-black, ...
// line-height - leading-none, leading-tight, leading-snug, leading-normal, leading-relaxed, ...
// text-align - text-left, text-center, text-right, text-justify, ...
// text-color - text-black, text-white, text-gray-500, ...
// Background

// background-color - bg-black, bg-white, bg-gray-500, ...
// background-image - bg-cover, bg-contain, bg-no-repeat, ...
// background-position - bg-top, bg-right, bg-bottom, bg-left, ...
// background-size - bg-auto, bg-cover, bg-contain, ...
// Borders

// border-width - border, border-2, border-4, ...
// border-style - border-solid, border-dashed, border-dotted, ...
// border-color - border-black, border-white, border-gray-500, ...
// border-radius - rounded, rounded-md, rounded-lg, ...
// Effects

// box-shadow - shadow, shadow-md, shadow-lg, ...
// opacity - opacity-50, opacity-75, opacity-100, ...
// transition - transition, transition-all, transition-colors, ...
// Interactivity

// cursor - cursor-pointer, cursor-not-allowed, cursor-text, ...
// pointer-events - pointer-events-none, pointer-events-auto, ...
// user-select - select-none, select-text, select-all, ...
// Responsive Design

// breakpoint -