import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [color, setColor] = useState("Olive")

  return (
    <div className="h-full w-full"style={{backgroundColor: color}}>

    
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <div className=" bg-white text-white flex-flex gap-2">
        <button onClick={() => setColor("red")}>Red</button>
        <button onClick={() => setColor("green")}>Green</button>
        <button onClick={() => setColor("blue")}>Blue</button>
        <button onClick={() => setColor("pink")} >Pink</button>
        <button onClick={() => setColor("brown")} >Brown</button>
        <button onClick={() => setColor("yellow")} >Yellow</button>
        <button onClick={() => setColor("purple")} >purple</button>
        <button onClick={() => setColor("orange")} >Orange</button>
      </div>
    </div>
  )
}

export default App

// Layout

// flex - flex
// inline-flex - inline-flex
// block - block
// inline-block - inline-block
// table - table
// inline-table - inline-table
// grid - grid
// inline-grid - inline-grid
// float - float-left, float-right, float-none
// clear - clear-left, clear-right, clear-both, clear-none
// overflow - overflow-auto, overflow-hidden, overflow-visible, overflow-scroll
// position - static, relative, absolute, fixed, sticky
// top - top-0, top-1, top-2, ...
// right - right-0, right-1, right-2, ...
// bottom - bottom-0, bottom-1, bottom-2, ...
// left - left-0, left-1, left-2, ...
// z-index - z-0, z-10, z-20, ...
// Spacing

// margin - m-0, m-1, m-2, ...
// margin-x - mx-0, mx-1, mx-2, ...
// margin-y - my-0, my-1, my-2, ...
// padding - p-0, p-1, p-2, ...
// padding-x - px-0, px-1, px-2, ...
// padding-y - py-0, py-1, py-2, ...
// gap - gap-0, gap-1, gap-2, ...
// Sizing

// width - w-full, w-1/2, w-1/3, ...
// height - h-full, h-1/2, h-1/3, ...
// max-width - max-w-full, max-w-md, max-w-lg, ...
// max-height - max-h-full, max-h-md, max-h-lg, ...
// min-width - min-w-full, min-w-md, min-w-lg, ...
// min-height - min-h-full, min-h-md, min-h-lg, ...
// Typography

// font-family - font-sans, font-serif, font-mono, ...
// font-size - text-xs, text-sm, text-base, text-lg, text-xl, ...
// font-weight - font-thin, font-light, font-normal, font-bold, font-black, ...
// line-height - leading-none, leading-tight, leading-snug, leading-normal, leading-relaxed, ...
// text-align - text-left, text-center, text-right, text-justify, ...
// text-color - text-black, text-white, text-gray-500, ...
// Background

// background-color - bg-black, bg-white, bg-gray-500, ...
// background-image - bg-cover, bg-contain, bg-no-repeat, ...
// background-position - bg-top, bg-right, bg-bottom, bg-left, ...
// background-size - bg-auto, bg-cover, bg-contain, ...
// Borders

// border-width - border, border-2, border-4, ...
// border-style - border-solid, border-dashed, border-dotted, ...
// border-color - border-black, border-white, border-gray-500, ...
// border-radius - rounded, rounded-md, rounded-lg, ...
// Effects

// box-shadow - shadow, shadow-md, shadow-lg, ...
// opacity - opacity-50, opacity-75, opacity-100, ...
// transition - transition, transition-all, transition-colors, ...
// Interactivity

// cursor - cursor-pointer, cursor-not-allowed, cursor-text, ...
// pointer-events - pointer-events-none, pointer-events-auto, ...
// user-select - select-none, select-text, select-all, ...
// Responsive Design

// breakpoint -